POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pcGEiLCJpZCI6IjY1MzEzYTJkYmRiYzUyM2VmMzY3ODc4NCIsImlhdCI6MTY5NzczNTI4M30.qJIPA5lkMGOG_rj47RcnLxA4iW_c5R8z-vs2It_0ktY

{
  "title": "The blog",
  "author": "Pena",
  "url": "something.com",
  "likes": 0
}