POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjUzMTNhMTliZGJjNTIzZWYzNjc4NzgyIiwiaWF0IjoxNzAxOTU0MjM5fQ.vQfETTKHbz1m2CtJwtljgrArYUf4XQ9y__M7bMfwmV0

{
  "title": "populate test",
  "author": "Pekka",
  "url": "test.com",
  "likes": 0
}